language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

sudo: false

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - vendor/bin/php-cs-fixer fix --dry-run -v --diff
    - wget https://scrutinizer-ci.com/ocular.phar
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

