build: false
shallow_clone: true
platform: 'x86'
clone_folder: C:\projects\ptmock

install:
  - cinst php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\ptmock
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction --dev

test_script:
  - cd C:\projects\ptmock
  - vendor\bin\phpunit.bat
